### ISSUE TITLE
Masrhmallow bug!

### ISSUE THREAD

**Issue by sagar-bharadwaj-ks** [SagarB-97/Grape#1]
Please correct the bug that causes app to crash when run on Marshmallow because of camera permission issues.

**Comment by jainsahab** [comment]
I'll take this up.

**Comment by sagar-bharadwaj-ks** [comment]
Yea Sure....Go ahead

**Comment by jainsahab** [comment]
[PR](https://github.com/SagarB-97/Grape/pull/7) created. Please have a look.

**Comment by sagar-bharadwaj-ks** [comment]
Thanks a lot @jainsahab .....I'll have a look at it tonight...:)

**Comment by jainsahab** [comment]
since PR is merged, we can close this issue as well.
